# environment.yml
name: dibs_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=2.1.0
  - torchvision=0.16.0
  - torchaudio=2.1.0
  - cpuonly # or cudatoolkit=11.8 for GPU
  - jupyterlab
  - mlflow
  - numpy=1.24.*
  - igraph
  - pandas
  - scikit-learn
  - python-igraph
  - matplotlib
  - networkx